name: Test cbftp-updater Script

on: [push, pull_request]

jobs:
  test-cbftp-updater-script:
    runs-on: ubuntu-22.04
    env:
      CB_USER: "runner"
      CB_SCREEN: "cbftp"
      CB_SERVICE: "cbftp.service"
      CB_DIR_SRC: "/home/runner/_downloads/cbftp"
      CB_DIR_DEST: "/home/runner/_autotrade/cbftp"
      CB_SVN_URL: "https://cbftp.glftpd.io/svn"
      CB_WEBSITE: "https://cbftp.glftpd.io/"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "Updating environment"
          sudo DEBIAN_FRONTEND="noninteractive" apt-get update
          echo "Installing dependencies"
          sudo apt-get install -y subversion build-essential screen libxml2-utils curl

      - name: Configure Environment and Variables
        run: |
          {
            echo "CB_USER=$CB_USER"
            echo "CB_SCREEN=$CB_SCREEN"
            echo "CB_SERVICE=$CB_SERVICE"
            echo "CB_DIR_SRC=$CB_DIR_SRC"
            echo "CB_DIR_DEST=$CB_DIR_DEST"
            echo "CB_SVN_URL=$CB_SVN_URL"
            echo "CB_WEBSITE=$CB_WEBSITE"
          } >> cbftp-updater.cfg
          cat cbftp-updater.cfg

      - name: Make cbftp-updater.sh Executable
        run: chmod +x ./cbftp-updater.sh

      - name: Run cbftp Updater Script
        run: sudo ./cbftp-updater.sh

      - name: Checkout Rollback SVN Revision
        run: |
          sudo rm -rf "$CB_DIR_SRC"
          sudo svn checkout -r 1244 "$CB_SVN_URL/cbftp" "$CB_DIR_SRC"

      - name: Run test updater script
        run: sudo ./cbftp-updater.sh

      - name: Make cbftp-crontab-installer.sh Executable
        run: chmod +x ./cbftp-crontab-installer.sh

      - name: Run cbftp Installer Script
        run: |
          sudo ./cbftp-crontab-installer.sh -h
          sudo ./cbftp-crontab-installer.sh -f hourly
          sudo ./cbftp-crontab-installer.sh -f weekly
          sudo ./cbftp-crontab-installer.sh -f weekly